echo "# https-github.com-yourusername-sql-learning-app" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/CSME030/https-github.com-yourusername-sql-learning-app.git
git push -u origin main
